export type ImageMap = {
  [key: string]: string[];
};
export const images: ImageMap = {
     education: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/education1.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education2.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education3.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education4.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education5.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education6.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education7.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education8.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education9.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education10.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education11.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education12.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education13.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/education14.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/campaign%201-%20post.jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Campaign%207.png",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Learnfella_ad-Data%20science3.jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Nest%20school%20-%20High%20School.jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Nest%20school%20-%20primary%20(1).jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Nest%20school%20-%20secondary%20(1).jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Nest_Poster_15_11_25_9_16.jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/ad%20wrkng-final-01.jpg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/ramadan-360.jpg.jpeg",
    "https://assets.rankraze.uk/wp-content/uploads/2026/360-post-5.jpg",
  ],
    healthcare: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/heathcare1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare7.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare8.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare9.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare10.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare11.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare12.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare13.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/healthcare/healthcare14.webp",
    ],
    food: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/food1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/food2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/food3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/food4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/food5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/Duty%20free%20Gif.gif",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/Fries.jpg",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/loaded%20fries.jpg",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/Smaak_bubble_tea_creative.jpg",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/Dubai%20Swirls.jpg",
      "https://assets.rankraze.uk/wp-content/uploads/2026/food/Churros.jpg",

    ],
    beauty: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty7.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Beauty8.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/beauty/Daily%20Veil%20-%2050ml%20with%20bg.jpg",
    ],
    bilingual: [
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual1.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual2.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual3.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual4.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual5.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual6.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual7.webp",
   "https://assets.rankraze.uk/wp-content/uploads/2026/Bilingual/Bilingual8.webp",
    ],
    branding: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/Branding7.gif",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Branding/basmathi%20frnt.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Branding/_AJR%20Label%2015%20litre.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/Branding/wheat%20flour%20500g-%20frnt.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Branding/pearl%20millet%20flour.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Branding/1000ml.png",

    ],
    clothing: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Clothing6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/clothing/AD-4-5-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/clothing/Elixelman%20post-1-.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/clothing/elixelman-meta%20ad%20poster--final.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/clothing/elixelman-meta%20ad%20poster.jpg",
    ],
    ecommerce: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce7.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ecommerce8.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/Ad-2-corrections-01-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/malayappa_07_08-1.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/pyrotown%20post--20-8.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/Ecommerce/pyrotown%20post-01-8-01.jpg",
    ],
    gardening: [
    "https://assets.rankraze.uk/wp-content/uploads/2026/gardening/Gardening1.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/gardening/Gardening2.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/gardening/Gardening3.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/gardening/Gardening4.webp",
    "https://assets.rankraze.uk/wp-content/uploads/2026/gardening/Gardening5.webp",
    ],
    it: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/it/it1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/it/it2.webp",
    ],
    logistics: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/Logistics6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/logistics7.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/logistics/logistics8.webp",
    ],
    others: [
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others1.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others2.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others3.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others4.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others5.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others6.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others7.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others8.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others9.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others10.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others11.gif",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others12.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others13.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others14.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others15.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others16.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others17.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others18.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others19.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others20.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others21.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others22.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/others23.webp",
      "https://assets.rankraze.uk/wp-content/uploads/2026/others/Plan_Oleo_Energy-23-08.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/others/Prajha%20Investor_AD-4-5.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/others/Uranus_Oil_Out.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/others/panoleo-1--1080.jpg",
      

    ],
    realestate: [
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate1.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate2.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate3.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate4.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate5.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate6.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate7.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate8.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate9.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate10.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate11.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate12.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate13.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate14.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/realestate15.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/Orchids_Ad.jpeg",
"https://assets.rankraze.uk/wp-content/uploads/2026/realestate/Prajha%20Investor_AD-4-5.jpg",


    ],
    product:[
      "https://assets.rankraze.uk/wp-content/uploads/2026/product/Pyro_town_10_07___Final.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/Pyro_town_14_08_25.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/pyrotown%20post-01-8-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/pyrotown%20post-01-8__-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/Pyrotown%20post-23-8.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/Pyrotown_Gnesh-charthurti.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/1_carausal_03_07.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/ad-03.webp",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/ArunExcello-FINAL.jpeg",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/DGrandeur_exhibitors_2.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/malayappa_18_07_.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/malayappa_poster_30_07.png",
"https://assets.rankraze.uk/wp-content/uploads/2026/product/Mariot-Jaipur_poster.webp",
    ],
    salon:[
      "https://assets.rankraze.uk/wp-content/uploads/2026/salon/template%202-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/salon/template%203-01.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/salon/Limelite-Poster01.jpeg",
    ],
    warehouse:[
"https://assets.rankraze.uk/wp-content/uploads/2026/warehouse/why%20choose%20warehouster.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/warehouse/Got%20space%20fyB.jpg",
"https://assets.rankraze.uk/wp-content/uploads/2026/warehouse/smm%20post%205.jpg",
    ],
};
export const categories: string[] = [
  "education",
  "healthcare",
  "food",
  "beauty",
  "gardening",
  "realestate",
  "clothing",
  "logistics",
  "it",
  "ecommerce",
  "bilingual",
  "branding",
  "product",
  "salon",
  "warehouse",
  "others",

];



export const videoIframe: ImageMap = {
  education: [
    "https://www.youtube.com/embed/jlBWalFDEuI?si=hAy0WkX7RAsdqmmF",
     "https://www.youtube.com/embed/PWb-c4Fn08o?si=I8he6JhPmrdQu_rJ",
     "https://www.youtube.com/embed/PkYCdajnVtk?si=Sq7yc4kr2GlM1Yxg",
     "https://www.youtube.com/embed/vCuLWZpdhqA?si=m4ZrzX09uSXQX-MV",
     "https://www.youtube.com/embed/j5J37nY4CVI?si=ngMbBsuqeBWaj_sj" ,
     "https://www.youtube.com/embed/RaF0KRVbkv8?si=RM0Ikg0xSZOCRsED" 

  ],
  food: [
    "https://www.youtube.com/embed/frgTQXhFF1A?si=Hxdjlf5ybJX82GSm",
    "https://www.youtube.com/embed/ywyAaWCJHow?si=IUyFV4rY13VRR1lo",

  ],
};


export const videoFiles: ImageMap = {
  education: [
    "https://assets.rankraze.uk/wp-content/uploads/2026/Web_dev_adv.mp4",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Ramya_video1_Final__.mp4",
    "https://assets.rankraze.uk/wp-content/uploads/2026/Nest_School_Ad_1_Final.mp4",
    "https://assets.rankraze.uk/wp-content/uploads/2026/360_Abrd_vid_02_Final_out.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/360_Abroad_Vid_04_.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/360_Degree_Abroad_vid_1_.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/360Abroad_vid_3_.mp4",
  ],
  food: [
   "https://assets.rankraze.uk/wp-content/uploads/2026/food/Smaak%20Ice%20Cream.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/food/Smaak_Bubble_tea__Final.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/food/Smaak_crepe.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/food/WAFFLE%20Challenge.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/food/HOT%20CHOCOLATE%20Gif.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/food/Treeya_Vid_Diwali_Final.mp4",

  ],
  others:[
    "https://assets.rankraze.uk/wp-content/uploads/2026/others/RR_Tower_CG_final.mp4",
"https://assets.rankraze.uk/wp-content/uploads/2026/others/Pan_Oleo_28_08_25.mp4"
  ],
};
